# Generated by Django 5.1.6 on 2025-02-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_vendor"),
        ("vendors", "0002_auto_20250130_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="vendors.vendor",
            ),
        ),
    ]
