# Generated by Django 5.1.5 on 2025-01-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
    ]
